#!/bin/bash

python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 2 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 3 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 4 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 5 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 6 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 7 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 8 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 9 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 10 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 11 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 12 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 13 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 14 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep1 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep2 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep3 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep4 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep5 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep6 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep7 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep8 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep9 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep10 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep11 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep12 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep13 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep14 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep15 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep16 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep17 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep18 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep19 &
python ~/trs_selection/src/fastStructure/structure.py -K 15 --input=data/gbs/g2f_hyb_bin --output=data/structure/g2f_hyb_rep20
